language: python
python:
  - "3.7"

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: "Install dependencies"
      script: pip install -r requirements.txt

    - stage: test
      name: "Unit tests"
      script: make test
    - stage: test
      name: "Code coverage"
      script: make cov
    - stage: test
      name: "Linter"
      script: make lint